---
language: go
install:
  - sudo apt-get update
  - sudo apt-get install at # for testing upstart
  - mkdir ~/go
  - go get -d -v ./... && go build -v ./...
go:
  - 1.4.1
  - tip
script: sudo GOPATH=$GOPATH PATH=$PATH `which go` test -v ./...
